FROM ghcr.io/open-webui/open-webui:slim

ENV USE_OLLAMA_DOCKER=false
ENV USE_CUDA_DOCKER=false
ENV USE_SLIM_DOCKER=true
ENV ANONYMIZED_TELEMETRY=false
ENV DO_NOT_TRACK=true
ENV SCARF_NO_ANALYTICS=true
ENV WEBUI_PORT=$PORT

EXPOSE 8080

CMD ["bash", "start.sh"]
