FROM ghcr.io/open-webui/open-webui:tiny

ENV USE_OLLAMA_DOCKER=false
ENV USE_CUDA_DOCKER=false
ENV ANONYMIZED_TELEMETRY=false
ENV DO_NOT_TRACK=true
ENV SCARF_NO_ANALYTICS=true
ENV OLLAMA_BASE_URL=""
ENV WEBUI_AUTH=false
ENV PORT=8080
ENV WEBUI_PORT=8080

EXPOSE 8080

CMD ["bash", "start.sh"]
